POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
	"name": "Heikki Kinnunen",
	"dateOfBirth": "1962-09-14",
	"ssn": "140962-213E",
	"gender": "male",
	"occupation": "actor"
}